LPS.Marketing.Main/LPS.Marketing.Main/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPS.Marketing.Main.Controllers
{
    public class JobsController : Controller
    {
        // GET: Jobs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CustomerServices(Model.Filters filters)
        {
            filters.job = "customer-service";

            string url = Repository.Repo.GetApiUrlForJobs(filters);

            var results = Repository.Repo.GetResults(url);
            
            return PartialView(results);
        }

        public ActionResult IT()
        {
            return View();
        }

        public ActionResult _IT(Model.Filters filters)
        {
            filters.job = "it";
            string url = Repository.Repo.GetApiUrlForJobs(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }

    }
}

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/CustomerServices.cshtml
@model IEnumerable<LPS.Marketing.Model.InnerResult>

@{
    ViewBag.Title = "CustomerServices";
}

@foreach (var item in Model)
{
    <div class="row thumbnail" style="" onmouseover="this.style.background = '#eeeeee';" onmouseout="this.style.background='white';">
        <div class="row">
            <div class="col-md-3">
                @if (@item.nopicture_label == null)
                {
                    <img border="0" src="~/Images/noImage.png" alt="right">
                }
                else
                {
                    <img border="0" src="@item.nopicture_label" alt="right">
                }
            </div>
            <div class="col-md-6">
                @{
                    string li = @item.linkwithhash_link;
                    string middl = li.Substring(li.LastIndexOf('/') + 1);
                    @ViewBag.Heading = middl.Substring(0, middl.LastIndexOf('-')).Replace("-", " ");
                }
                <h3>@ViewBag.Heading</h3>
                <div class="caption">
                    <p>
                        @if (@item.breadcrumb_value != null)
                        {
                            <img src="~/Images/Annotation.png" />
                            <a href="https://www.google.com/maps/place/@item.breadcrumb_value,+Pakistan" target="_blank">
                               @item.breadcrumb_value
                            </a>
                        }
                    </p>
                    <p>
                        @if (@item.breadcrumb_flag != null)
                        {
                            @item.breadcrumb_flag
                        }
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <h3>@item.c000_value</h3>
                <p>
                    <a href=@item.linkwithhash_link target="_blank">
                        <h5>Details</h5>
                    </a>
                </p>
            </div>
        </div>
    </div>
    <br />
}

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/IT.cshtml
@{
    ViewBag.Title = "IT";
}

<div class="row">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div>
                    <img src="~/Images/InformationTechnology.png" alt="Cars">
                </div>
            </div>
            <div class="col-lg-9">
                <div class="jumbotron" style="padding-top: 10px; padding-bottom: 10px">
                    @Html.Partial("_JobsFilterForm")
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation"><a href="@Url.Action("Index","Jobs")">Customer Services</a></li>
                    <li role="presentation" class="active"><a href="@Url.Action("IT","Jobs")">IT</a></li>
                    @*<li role="presentation"><a href="@Url.Action("Online","Jobs")">Online</a></li>
                    <li role="presentation"><a href="@Url.Action("Marketing","Jobs")">Marketing</a></li>
                    <li role="presentation"><a href="@Url.Action("Advertisement","Jobs")">Advertisiment and PR</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Sales</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Clerical And ADministration</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Human Resource</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Education</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Hotels and Tourism</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Accounting and Finance</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Manufacturing</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Part TIme</a></li>
                    <li role="presentation"><a href="@Url.Action("#","Jobs")">Other Jobs</a></li>*@
                </ul>
            </div>
            <div class="col-lg-9">
                <div id="divWrapper">
                    @{ Html.RenderAction("_IT", "Jobs"); }
                </div>
            </div>
        </div>
        <hr>
        <footer>
            <p>&copy; 2016 LPS, Inc.</p>
        </footer>
    </div>
</div>

<script src="~/Scripts/waitMe.js"></script>
<script>
    var current_effect = "img";

    function GenerateResults() {
        activateLoader();
        var param = {
            position: $('#position').val(),
            salaryFrom: $('#salaryFrom').val(),
            salaryTo: $('#salaryTo').val(),
        };
        $.ajax(
            {
                type: 'POST',
                url: '@Url.Action("_IT", "Jobs")',
                dataType: "html",
                data: param,
                success: function (result) {
                    deActivateLoader();
                    $('#divWrapper').html(result);
                },
                error: function () {
                    deActivateLoader();
                    alert("Some Thing Went Wrog Please Try later.");
                }
       });
    }

    function activateLoader() {
        run_waitMe(current_effect);
    }

    function deActivateLoader() {
        $('body').waitMe('hide');
    }

    function run_waitMe(effect) {
        $('body').waitMe({
            effect: effect,
            text: 'Please wait...',
            bg: 'rgba(255,255,255,0.7)',
            color: '#000',
            sizeW: '',
            sizeH: '',
            source: 'img.svg',
            onClose: function () { }
        });
    }

</script>

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/Index.cshtml
@{
    ViewBag.Title = "CustomerServices";
}

<div class="row">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div>
                    <img src="~/Images/CustomerServices.png" alt="Cars">
                </div>
            </div>
            <div class="col-lg-9">
                <div class="jumbotron" style="padding-top: 10px; padding-bottom: 10px">
                    @Html.Partial("_JobsFilterForm")
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation" class="active"><a href="@Url.Action("Index","Jobs")">Customer Services</a></li>
                    <li role="presentation"><a href="@Url.Action("IT","Jobs")">IT</a></li>
                    @*<li role="presentation"><a href="@Url.Action("Online","Jobs")">Online</a></li>
                    <li role="presentation"><a href="@Url.Action("Marketing","Jobs")">Marketing</a></li>
                    <li role="presentation"><a href="@Url.Action("Advertisement","Jobs")">Advertisiment and PR</a></li>
                    <li role="presentation"><a href="@Url.Action("Sales","Jobs")">Sales</a></li>
                    <li role="presentation"><a href="@Url.Action("Administration","Jobs")">Clerical And ADministration</a></li>
                    <li role="presentation"><a href="@Url.Action("HumanResources","Jobs")">Human Resource</a></li>
                    <li role="presentation"><a href="@Url.Action("Tourism","Jobs")">Hotels and Tourism</a></li>
                    <li role="presentation"><a href="@Url.Action("Finance","Jobs")">Accounting and Finance</a></li>
                    <li role="presentation"><a href="@Url.Action("Manufacturing","Jobs")">Manufacturing</a></li>
                    <li role="presentation"><a href="@Url.Action("Parttime","Jobs")">Part TIme</a></li>
                    <li role="presentation"><a href="@Url.Action("Otherjobs","Jobs")">Other Jobs</a></li>*@
                </ul>
            </div>
            <div class="col-lg-9">
                <div id="divWrapper">
                    @{ Html.RenderAction("CustomerServices", "Jobs"); }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/waitMe.js"></script>
<script>
    var current_effect = "img";

    function GenerateResults() {
        activateLoader();
        var param = {
            position: $('#position').val(),
            salaryFrom: $('#salaryFrom').val(),
            salaryTo: $('#salaryTo').val(),
        };
        $.ajax(
            {
                type: 'POST',
                url: '@Url.Action("CustomerServices", "Jobs")',
                dataType: "html",
                data: param,
                success: function (result) {
                    deActivateLoader();
                    $('#divWrapper').html(result);
                },
                error: function () {
                    deActivateLoader();
                    alert("Some Thing Went Wrog Please Try later.");
                }
       });
    }

    function activateLoader() {
        run_waitMe(current_effect);
    }

    function deActivateLoader() {
        $('body').waitMe('hide');
    }

    function run_waitMe(effect) {
        $('body').waitMe({
            effect: effect,
            text: 'Please wait...',
            bg: 'rgba(255,255,255,0.7)',
            color: '#000',
            sizeW: '',
            sizeH: '',
            source: 'img.svg',
            onClose: function () { }
        });
    }

</script>

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/_IT.cshtml
@model IEnumerable<LPS.Marketing.Model.InnerResult>

@{
    ViewBag.Title = "IT";
}

@foreach (var item in Model)
{
    <div class="row thumbnail" style="" onmouseover="this.style.background = '#eeeeee';" onmouseout="this.style.background='white';">
        <div class="row">
            <div class="col-md-3">
                @if (@item.nopicture_label == null)
                {
                    <img border="0" src="~/Images/noImage.png" alt="right">
                }
                else
                {
                    <img border="0" src="@item.nopicture_label" alt="right">
                }
            </div>
            <div class="col-md-6">
                @{
                    string li = @item.linkwithhash_link;
                    string middl = li.Substring(li.LastIndexOf('/') + 1);
                    @ViewBag.Heading = middl.Substring(0, middl.LastIndexOf('-')).Replace("-", " ");
                }
                <h3>@ViewBag.Heading</h3>
                <div class="caption">
                    <h4>
                        @if (@item.breadcrumb_value != null)
                        {
                            @item.breadcrumb_value
                        }
                        @if (@item.jobsit_label != null)
                        {
                            @item.jobsit_label
                        }
                    </h4>
                    <p>
                        @if (@item.breadcrumb_flag != null)
                        {
                            @item.breadcrumb_flag
                        }
                        @if (@item.jobsit_value != null)
                        {
                            <img src="~/Images/Annotation.png" />
                            <a href="https://www.google.com/maps/place/@item.jobsit_value,+Pakistan" target="_blank">
                                @item.jobsit_value
                            </a>
                        }
                    </p>
                </div>
            </div>
            <div class="col-md-3">
                <h3>@item.c000_value</h3>
                <p>
                    <a href=@item.linkwithhash_link target="_blank">
                        <h5>Details</h5>
                    </a>
                </p>
            </div>
        </div>
    </div>
    <br />
}

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/_JobsFilterForm.cshtml
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/lpsMarketing.js"></script>

<div class="row">
    <div class="col-md-3">
        <h5>Position:</h5>
        <select id="position" name="position" class="form-control">
            <option value="Position" style="display:none">Position Type</option>
            <option value="customer-service">All</option>
            <option value="fulltime">Full Time</option>
            <option value="parttime">Part Time</option>
            <option value="contract">Contract</option>
            <option value="temporary">Temporary</option>
        </select>
    </div>
    <div class="col-md-6">
        <h5>Salary Range:&nbsp;<span id="errmsg" class="text-danger"></span></h5>
        <div class="row">
            <div class="col-md-4">
                <input name="salaryFrom" id="salaryFrom" class="form-control" style="width:100px" placeholder="From" />
            </div>
            <div class="col-md-4">
                <input name="salaryTo" id="salaryTo" class="form-control" style="width:100px" placeholder="From" />
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <h5>&nbsp;</h5>
        <button class="btn btn-success form-control" onclick="GenerateResults()">Filter</button>
    </div>
</div>

LPS.Marketing.Main/LPS.Marketing.Main/Views/Jobs/_JobsNavBar.cshtml
<ul class="nav nav-pills nav-stacked">
    <li role="presentation" class="active" onclick=""><a href="@Url.Action("Index","Jobs")">Customer Services</a></li>
    <li role="presentation"><a href="@Url.Action("IT","Jobs")">IT</a></li>
    <li role="presentation"><a href="@Url.Action("Online","Jobs")">Online</a></li>
    <li role="presentation"><a href="@Url.Action("Marketing","Jobs")">Marketing</a></li>
    <li role="presentation"><a href="@Url.Action("Advertisement","Jobs")">Advertisiment and PR</a></li>
    <li role="presentation"><a href="@Url.Action("Sales","Jobs")">Sales</a></li>
    <li role="presentation"><a href="@Url.Action("Administration","Jobs")">Clerical And ADministration</a></li>
    <li role="presentation"><a href="@Url.Action("HumanResources","Jobs")">Human Resource</a></li>
    <li role="presentation"><a href="@Url.Action("Tourism","Jobs")">Hotels and Tourism</a></li>
    <li role="presentation"><a href="@Url.Action("Finance","Jobs")">Accounting and Finance</a></li>
    <li role="presentation"><a href="@Url.Action("Manufacturing","Jobs")">Manufacturing</a></li>
    <li role="presentation"><a href="@Url.Action("Parttime","Jobs")">Part TIme</a></li>
    <li role="presentation"><a href="@Url.Action("Otherjobs","Jobs")">Other Jobs</a></li>
</ul>

<script>
    $(document).ready(function () {
        $('.nav li a').click(function (e) {

            $('.nav li').removeClass('active');

            var $parent = $(this).parent();
            if (!$parent.hasClass('active')) {
                $parent.addClass('active');
            }
        });
    });
</script>