LPS.Marketing.Main/LPS.Marketing.Main/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPS.Marketing.Main.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LPS.Marketing.Main/LPS.Marketing.Main/Controllers/RealEstateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPS.Marketing.Main.Controllers
{
    public class RealEstateController : Controller
    {
        // GET: RealEstate
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Houses(Model.Filters filters)
        {
            if (filters.realEstate == null || filters.realEstate == "Category")
            {
                filters.realEstate = "houses";
            }
            string url = Repository.Repo.GetApiUrlForRealestate(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }

        public ActionResult Apartments()
        {
            return View();
        }

        public ActionResult _Appartment(Model.Filters filters)
        {
            if (filters.realEstate == null || filters.realEstate == "Category")
            {
                filters.realEstate = "apartments";
            }
            string url = Repository.Repo.GetApiUrlForRealestate(filters);
            var results = Repository.Repo.GetResults(url);
            return View(results);
        }

        public ActionResult Roommates()
        {
            return View();
        }

        public ActionResult _Roommates(Model.Filters filters)
        {
            filters.realEstate = "pg-roommates";
            string url = Repository.Repo.GetApiUrlForRealestate(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }

        public ActionResult LandPlots()
        {
            return View();
        }

        public ActionResult _LandPlots(Model.Filters filters)
        {
            if (filters.realEstate == null || filters.realEstate == "Category")
            {
                filters.realEstate = "land-plots";
            }

            string url = Repository.Repo.GetApiUrlForRealestate(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }

        public ActionResult CommercialSpace()
        {
            return View();
        }

        public ActionResult _CommercialSpace(Model.Filters filters)
        {
            if (filters.realEstate == null || filters.realEstate == "Category")
            {
                filters.realEstate = "commercial-space";
            }

            string url = Repository.Repo.GetApiUrlForRealestate(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }
        
        public ActionResult GuestHouse()
        {
            return View();
        }

        public ActionResult _GuestHouse(Model.Filters filters)
        {
            filters.realEstate = "guest-houses";

            string url = Repository.Repo.GetApiUrlForRealestate(filters);

            var results = Repository.Repo.GetResults(url);
            
            return View(results);
        }
    }
}

LPS.Marketing.Main/LPS.Marketing.Main/Controllers/VechilesController.cs
using LPS.Marketing.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPS.Marketing.Main.Controllers
{
    public class VechilesController : Controller
    {
        // GET: Vechiles
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cars(Model.Filters filters)
        {
            if (filters.vechiels == null)
            {
                filters.vechiels = "cars";
            }
            else if (filters.vechiels == "brand")
            {
                filters.vechiels = "cars";
            }

            string url = Repository.Repo.GetApiUrlForVechiles(filters);

            var result = Repository.Repo.GetResults(url);

            return PartialView(result);
        }

        public ActionResult Commerical()
        {
            return View();
        }

        public ActionResult CommericalVechiles(Model.Filters filters)
        {
            filters.vechiels = "commercial-vehicles";

            string url = Repository.Repo.GetApiUrlForVechiles(filters);
            var results = Repository.Repo.GetResults(url);
            
            return PartialView(results);
        }

        public ActionResult Other()
        {
            return View();
        }
        
        public ActionResult OtherVechiles(Model.Filters filters)
        {
            filters.vechiels = "other-vehicles/";

            string url = Repository.Repo.GetApiUrlForVechiles(filters);
            var results = Repository.Repo.GetResults(url);
            
            return PartialView(results);
        }

        public ActionResult PakWheels()
        {
            return View();
        }

        public ActionResult _PakWheels(Model.Filters filters)
        {
            string url = Repository.Repo.GetApiUrlForPakWheels(filters);
            var results = Repository.Repo.GetResults(url);
            return PartialView(results);
        }
    }
}

LPS.Marketing.Main/LPS.Marketing.Main/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LPS.Marketing.Main/LPS.Marketing.Main/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LPS.Marketing.Main/LPS.Marketing.Main/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <hr />
    <div class="col-md-2 thumbnail" style="border:solid 2px; border-radius: 5px; text-align:center">
        <a href="@Url.Action("Index","Vechiles")">
            <img src="~/Images/Car.png" alt="Cars">
        </a>
        <h3>Vechiles</h3>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-2" style="border:solid 2px; border-radius: 5px; text-align:center">
        <a href="@Url.Action("Index","RealEstate")">
            <img src="~/Images/Property .png" alt="Jobs">
        </a>
        <h3>Real Estate</h3>
    </div>
    <div class="col-md-3">
    </div>
    <div class="col-md-2" style="border:solid 2px; border-radius: 5px; text-align:center">
        <a href="@Url.Action("Index","Jobs")">
            <img src="~/Images/Jobs.png" alt="Jobs">
        </a>
        <h3>Jobs</h3>
    </div>
</div>